import { Edges } from '@react-three/drei';

/** Open-front schematic enclosure: the colored route termination dots sit inside the box. */
export function JunctionBox3D({ size, color, selected = false }: { size: [number,number,number]; color: string; selected?: boolean }) {
  const thickness = Math.max(.012, Math.min(size[0], size[1], size[2]) * .09);
  const frameColor = selected ? '#4ce1a1' : color;
  const panel = (key: string, position: [number,number,number], dimensions: [number,number,number]) => <mesh key={key} position={position}>
    <boxGeometry args={dimensions} /><meshStandardMaterial color={frameColor} roughness={.78} /><Edges color="#d7e1e4" threshold={15} />
  </mesh>;
  const innerFace = -size[2] / 2 + thickness + .004;
  return <group>
    {panel('back', [0,0,-size[2] / 2 + thickness / 2], [size[0],size[1],thickness])}
    {panel('left', [-size[0] / 2 + thickness / 2,0,0], [thickness,size[1],size[2]])}
    {panel('right', [size[0] / 2 - thickness / 2,0,0], [thickness,size[1],size[2]])}
    {panel('top', [0,size[1] / 2 - thickness / 2,0], [size[0],thickness,size[2]])}
    {panel('bottom', [0,-size[1] / 2 + thickness / 2,0], [size[0],thickness,size[2]])}
    {[-.22,.22].map((offset) => <mesh key={offset} position={[size[0] * offset,0,innerFace]}><cylinderGeometry args={[Math.min(size[0],size[1]) * .075,Math.min(size[0],size[1]) * .075,thickness * .75,16]} /><meshStandardMaterial color="#c7d0d3" /></mesh>)}
  </group>;
}

/** Small schematic features that make important technical equipment recognisable without photorealism. */
export function DeviceDetails3D({ typeId, size, color }: { typeId: string; size: [number,number,number]; color: string }) {
  const front = size[2] / 2 + .004; const dark = '#263238';
  if (['outdoor-unit','heat-pump'].includes(typeId)) return <><mesh position={[0,0,front]} rotation={[Math.PI / 2,0,0]}><torusGeometry args={[Math.min(size[0],size[1]) * .28,.028,12,36]} /><meshStandardMaterial color={dark} /></mesh><mesh position={[0,0,front + .003]}><circleGeometry args={[Math.min(size[0],size[1]) * .22,28]} /><meshStandardMaterial color="#53656c" /></mesh>{[-1,0,1].map((index) => <mesh key={index} position={[0,0,front + .008]} rotation={[0,0,index * Math.PI / 3]}><boxGeometry args={[.025,Math.min(size[0],size[1]) * .38,.012]} /><meshBasicMaterial color="#1b2529" /></mesh>)}</>;
  if (typeId === 'indoor-unit') return <>{Array.from({ length: 7 }, (_, index) => <mesh key={index} position={[-size[0] * .36 + index * size[0] * .12,-size[1] * .28,front]}><boxGeometry args={[size[0] * .065,.018,.016]} /><meshBasicMaterial color={dark} /></mesh>)}<mesh position={[size[0] * .35,size[1] * .22,front]}><boxGeometry args={[size[0] * .12,size[1] * .08,.012]} /><meshBasicMaterial color="#9fd7d0" /></mesh></>;
  if (typeId === 'boiler') return <><mesh position={[0,size[1] * .16,front]}><boxGeometry args={[size[0] * .34,size[1] * .13,.018]} /><meshBasicMaterial color="#20343b" /></mesh><mesh position={[0,-size[1] * .1,front]}><circleGeometry args={[Math.min(size[0],size[1]) * .08,20]} /><meshStandardMaterial color="#9aabb1" /></mesh>{[-.28,-.09,.09,.28].map((offset) => <mesh key={offset} position={[size[0] * offset,-size[1] / 2 - .035,0]}><cylinderGeometry args={[.018,.018,.07,12]} /><meshStandardMaterial color={offset < 0 ? '#2c8f73' : '#b55b50'} /></mesh>)}</>;
  if (typeId === 'radiator') return <>{Array.from({ length: 9 }, (_, index) => <mesh key={index} position={[-size[0] * .42 + index * size[0] * .105,0,front]}><boxGeometry args={[size[0] * .055,size[1] * .86,.018]} /><meshStandardMaterial color="#d9dedf" /></mesh>)}</>;
  if (typeId === 'access-point') return <><mesh position={[0,0,front]}><ringGeometry args={[Math.min(size[0],size[1]) * .13,Math.min(size[0],size[1]) * .19,24]} /><meshBasicMaterial color="#d9e2e5" /></mesh><mesh position={[0,0,front + .002]}><circleGeometry args={[.008,14]} /><meshBasicMaterial color="#45d99a" /></mesh></>;
  if (typeId === 'switch') return <><mesh position={[0,0,front + .006]} rotation={[-.16,0,0]}><boxGeometry args={[size[0] * .48,size[1] * .62,.018]} /><meshStandardMaterial color="#e8edef" roughness={.7} /></mesh><mesh position={[0,size[1] * .19,front + .019]}><circleGeometry args={[.007,12]} /><meshBasicMaterial color="#45d99a" /></mesh></>;
  if (typeId === 'tv-antenna') return <><mesh position={[0,0,front + .015]}><boxGeometry args={[size[0] * .82,.025,.025]} /><meshStandardMaterial color={dark} /></mesh>{[-.34,-.22,-.1,.1,.22,.34].map((offset) => <mesh key={offset} position={[size[0] * offset,0,front + .02]}><boxGeometry args={[.018,size[1] * (.48 + Math.abs(offset) * .45),.018]} /><meshStandardMaterial color="#8fa1a8" /></mesh>)}<mesh position={[0,-size[1] * .34,front + .025]}><boxGeometry args={[.035,size[1] * .3,.035]} /><meshStandardMaterial color={dark} /></mesh></>;
  if (typeId === 'fwa-antenna') return <><mesh position={[0,0,front + .008]}><ringGeometry args={[Math.min(size[0],size[1]) * .19,Math.min(size[0],size[1]) * .23,28]} /><meshStandardMaterial color="#dbe4e7" /></mesh><mesh position={[0,0,front + .012]}><circleGeometry args={[Math.min(size[0],size[1]) * .055,18]} /><meshBasicMaterial color={color} /></mesh></>;
  if (typeId === 'furniture-sink') return <><mesh position={[0,size[1] / 2 + .02,0]}><boxGeometry args={[size[0] * .62,.035,size[2] * .58]} /><meshStandardMaterial color="#9fb3b9" /></mesh><mesh position={[0,size[1] / 2 + .13,-size[2] * .15]}><cylinderGeometry args={[.018,.018,.23,12]} /><meshStandardMaterial color="#66777e" /></mesh></>;
  if (typeId === 'network-switch') return <>{Array.from({ length: 12 }, (_, index) => <mesh key={index} position={[-size[0] * .42 + index * size[0] * .076,0,front]}><boxGeometry args={[size[0] * .045,size[1] * .28,.012]} /><meshBasicMaterial color={index % 2 ? '#152126' : color} /></mesh>)}</>;
  if (['power-outlet','appliance-connection'].includes(typeId)) return <>{[-.18,.18].map((offset) => <mesh key={offset} position={[size[0] * offset,0,front]}><circleGeometry args={[Math.min(size[0],size[1]) * .07,14]} /><meshBasicMaterial color={dark} /></mesh>)}<mesh position={[0,-size[1] * .19,front]}><boxGeometry args={[size[0] * .18,.012,.012]} /><meshBasicMaterial color="#66a46f" /></mesh></>;
  if (['ethernet-outlet','fibre-termination'].includes(typeId)) return <><mesh position={[0,-size[1] * .04,front]}><boxGeometry args={[size[0] * .34,size[1] * .28,.014]} /><meshBasicMaterial color="#1d3038" /></mesh><mesh position={[0,size[1] * .25,front]}><boxGeometry args={[size[0] * .45,.012,.012]} /><meshBasicMaterial color="#3d91c8" /></mesh></>;
  if (typeId === 'electrical-panel') return <>{Array.from({ length: 4 }, (_, row) => Array.from({ length: 8 }, (_, column) => <mesh key={`${row}-${column}`} position={[-size[0] * .36 + column * size[0] * .103,size[1] * .3 - row * size[1] * .2,front]}><boxGeometry args={[size[0] * .065,size[1] * .09,.018]} /><meshStandardMaterial color={row % 2 ? '#67747a' : '#d6dde0'} /></mesh>))}<mesh position={[0,-size[1] * .4,front]}><boxGeometry args={[size[0] * .72,.018,.018]} /><meshBasicMaterial color="#d08835" /></mesh></>;
  if (['transformer','power-supply','ups','solar-battery-storage'].includes(typeId)) return <>{Array.from({ length: 5 }, (_, index) => <mesh key={index} position={[-size[0] * .3 + index * size[0] * .15,size[1] * .2,front]}><boxGeometry args={[size[0] * .07,.015,.012]} /><meshBasicMaterial color={dark} /></mesh>)}<mesh position={[0,-size[1] * .18,front]}><boxGeometry args={[size[0] * .28,size[1] * .13,.015]} /><meshBasicMaterial color="#79b7ac" /></mesh></>;
  if (['router','gateway','automation-controller'].includes(typeId)) return <><mesh position={[-size[0] * .35,size[1] * .43,0]}><cylinderGeometry args={[.008,.008,size[1] * .9,8]} /><meshStandardMaterial color={dark} /></mesh><mesh position={[size[0] * .35,size[1] * .43,0]}><cylinderGeometry args={[.008,.008,size[1] * .9,8]} /><meshStandardMaterial color={dark} /></mesh>{[-.22,0,.22].map((offset) => <mesh key={offset} position={[size[0] * offset,-size[1] * .12,front]}><circleGeometry args={[Math.max(.004,Math.min(size[0],size[1]) * .035),12]} /><meshBasicMaterial color="#54d78b" /></mesh>)}</>;
  if (['patch-panel','server','nas'].includes(typeId)) return <>{Array.from({ length: typeId === 'patch-panel' ? 12 : 6 }, (_, index) => <mesh key={index} position={[-size[0] * .4 + index * size[0] * (typeId === 'patch-panel' ? .073 : .16),0,front]}><boxGeometry args={[size[0] * (typeId === 'patch-panel' ? .045 : .11),size[1] * .38,.014]} /><meshStandardMaterial color={index % 2 ? '#41535a' : '#202e33'} /></mesh>)}</>;
  if (['motion-sensor','smoke-detector','co-detector','multi-detector','smart-sensor'].includes(typeId)) return <><mesh position={[0,0,front]}><ringGeometry args={[Math.min(size[0],size[1]) * .22,Math.min(size[0],size[1]) * .32,24]} /><meshStandardMaterial color="#e1e7e8" /></mesh>{[-.22,0,.22].map((offset) => <mesh key={offset} position={[size[0] * offset,-size[1] * .23,front + .002]}><circleGeometry args={[.006,10]} /><meshBasicMaterial color={offset ? '#6d7e84' : '#e05b4f'} /></mesh>)}</>;
  if (['thermostat','temperature-sensor','alarm-panel','intercom','video-intercom'].includes(typeId)) return <><mesh position={[0,size[1] * .1,front]}><boxGeometry args={[size[0] * .58,size[1] * .31,.014]} /><meshBasicMaterial color="#a8d8d1" /></mesh><mesh position={[0,-size[1] * .27,front]}><circleGeometry args={[Math.min(size[0],size[1]) * .07,14]} /><meshBasicMaterial color={dark} /></mesh></>;
  if (['air-vent','duct-endpoint'].includes(typeId)) return <>{Array.from({ length: 7 }, (_, index) => <mesh key={index} position={[0,-size[1] * .34 + index * size[1] * .11,front]}><boxGeometry args={[size[0] * .78,.012,.014]} /><meshBasicMaterial color="#56686f" /></mesh>)}</>;
  if (['hvac-manifold','plumbing-manifold','underfloor-connection'].includes(typeId)) return <>{[-.32,-.16,0,.16,.32].map((offset) => <mesh key={offset} position={[size[0] * offset,-size[1] * .35,front]}><cylinderGeometry args={[.018,.018,size[1] * .28,12]} /><meshStandardMaterial color={offset < 0 ? '#4f8eb4' : '#b35a50'} /></mesh>)}</>;
  if (['water-inlet','water-outlet','hot-water','cold-water','valve','pump'].includes(typeId)) return <><mesh position={[0,0,front]}><torusGeometry args={[Math.min(size[0],size[1]) * .25,.015,10,24]} /><meshStandardMaterial color={typeId.includes('hot') ? '#b65b52' : '#4a91b7'} /></mesh><mesh position={[0,0,front + .006]} rotation={[0,0,Math.PI / 4]}><boxGeometry args={[size[0] * .55,.018,.014]} /><meshBasicMaterial color={dark} /></mesh></>;
  if (['relay','smart-switch','motor-controller'].includes(typeId)) return <>{[-.2,.2].map((offset) => <mesh key={offset} position={[size[0] * offset,0,front]}><boxGeometry args={[size[0] * .18,size[1] * .52,.014]} /><meshStandardMaterial color="#35474e" /></mesh>)}<mesh position={[0,size[1] * .31,front]}><circleGeometry args={[.006,12]} /><meshBasicMaterial color="#e49a42" /></mesh></>;
  return null;
}
