[package]
name = "house-infrastructure-studio"
version = "0.2.11"
description = "Local residential infrastructure documentation editor"
authors = ["Luigi Casagrande"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
