export const en: Record<string, string> = {
  'Infrastructure editor · Local only': 'Infrastructure editor · Local only',
  'Editor': 'Editor', 'Overview': 'Overview', 'Settings': 'Settings', 'Projects': 'Projects', 'Saved': 'Saved', 'Saving…': 'Saving…', 'Save error': 'Save error',
  'X-ray': 'X-ray', 'X-ray ON': 'X-ray ON', 'Normal view': 'Normal view', 'Inside walls': 'Inside walls', 'Isolate room': 'Isolate room', 'Isolate wall': 'Isolate wall',
  'Perspective': 'Perspective', 'Orthographic': 'Orthographic', 'Views': 'Views', 'Top': 'Top', 'Isometric': 'Isometric', 'Fit full house': 'Fit full house', 'Fit selection': 'Fit selection', 'Export': 'Export',
  'Selected wall scheme': 'Selected wall scheme', 'Batch wall schemes': 'Batch wall schemes', 'Project backup': 'Project backup', 'Import backup': 'Import backup',
  'Active level': 'Active level', 'Manage levels and blueprints': 'Manage levels and blueprints', 'Elevation': 'Elevation', 'Ceiling height': 'Ceiling height', 'Full house': 'Full house', 'Adjacent blueprint': 'Adjacent blueprint', 'Below': 'Below', 'Above': 'Above',
  'Create': 'Create', 'Wall': 'Wall', 'Ceiling': 'Ceiling', 'Wall mounted': 'Wall mounted', 'Ceiling mounted': 'Ceiling mounted', 'Room': 'Room', 'Structure': 'Structure', 'Device': 'Device', 'Route': 'Route', 'Container': 'Container', 'Measure': 'Measure', 'Select': 'Select',
  'Room from selected walls': 'Room from selected walls', 'New wall thickness': 'New wall thickness', 'House structure': 'House structure', 'Column': 'Column', 'Device catalogue': 'Device catalogue', '+ Custom': '+ Custom',
  'Technical containers': 'Technical containers', 'Route setup': 'Route setup', 'Cable': 'Cable', 'Pipe': 'Pipe', 'Duct': 'Duct', 'Junction': 'Junction', 'Service': 'Service',
  'Measurement mode': 'Measurement mode', '3D distance': '3D distance', 'Vertical height': 'Vertical height', 'Services visibility': 'Services visibility', 'All': 'All', 'None': 'None', 'Rooms': 'Rooms', '+ Category': '+ Category',
  'No rooms defined.': 'No rooms defined.', 'Uncategorized': 'Uncategorized', 'Edit': 'Edit', 'Custom': 'Custom',
  'Choose any service-compatible first port. The second port will be limited to the coherent direction.': 'Choose any service-compatible first port. The second port will be limited to the coherent direction.',
  'Only a port coherent with the first endpoint direction can finish this route.': 'Only a port coherent with the first endpoint direction can finish this route.',
  'Wrong direction': 'Wrong direction',
  'Add another port': 'Add another port', 'New input': 'New input', 'New output': 'New output', 'Automatically placed inside the enclosure; its size grows when required.': 'Automatically placed inside the enclosure; its size grows when required.',
  'Editor settings': 'Editor settings', 'Project-specific drafting, route-planning, and visual rules': 'Project-specific drafting, route-planning, and visual rules', 'Route planning': 'Route planning',
  'Organize path, separation, turn, and identification rules for technical routes.': 'Organize path, separation, turn, and identification rules for technical routes.',
  'Path rules': 'Path rules', 'Avoid unrelated route conflicts': 'Avoid unrelated route conflicts', 'Strongly group routes sharing a destination': 'Strongly group routes sharing a destination', 'Floor route offset': 'Floor route offset',
  'Floor service stack': 'Floor service stack', 'Move deeper': 'Move deeper', 'Move closer to floor': 'Move closer to floor', 'Avoidance tiers': 'Avoidance tiers', 'Minimum side-by-side separation': 'Minimum side-by-side separation', 'Turn curvature': 'Turn curvature',
  'Route identification': 'Route identification', 'Naming pattern': 'Naming pattern', 'Example': 'Example',
  'Routes inside walls use only wall-local horizontal and vertical runs. Floor and ceiling paths use the configured service bend radius.': 'Routes inside walls use only wall-local horizontal and vertical runs. Floor and ceiling paths use the configured service bend radius.',
  'Adds an equivalent distance cost to each turn so route choices favor fewer corners.': 'Adds an equivalent distance cost to each turn so route choices favor fewer corners.', 'Negative values move the route inside and above the finished ceiling surface.': 'Negative values move the route inside and above the finished ceiling surface.', 'Sets the route reference plane below the finished floor surface.': 'Sets the route reference plane below the finished floor surface.',
  'Order of concealed floor services from deepest to closest to the finished floor. Vertical placement uses each service minimum side-by-side separation.': 'Order of concealed floor services from deepest to closest to the finished floor. Vertical placement uses each service minimum side-by-side separation.', 'Tier 1 receives the most protected path when services compete for space.': 'Tier 1 receives the most protected path when services compete for space.', 'Set the conflict-avoidance priority for this service.': 'Set the conflict-avoidance priority for this service.',
  'This value separates bundled routes laterally and also separates adjacent floor service tiers.': 'This value separates bundled routes laterally and also separates adjacent floor service tiers.', 'Minimum centerline separation for this service.': 'Minimum centerline separation for this service.', 'Floor and ceiling corners use the service bend radius. Transitions into walls are automatically reduced to stay inside the wall lining or structural core.': 'Floor and ceiling corners use the service bend radius. Transitions into walls are automatically reduced to stay inside the wall lining or structural core.', 'Preferred bend radius for this service on floor and ceiling paths.': 'Preferred bend radius for this service on floor and ceiling paths.',
  'Route identifiers remain unique and documented; service prefixes are project conventions.': 'Route identifiers remain unique and documented; service prefixes are project conventions.', 'Available tokens: {PREFIX}, {FLOOR}, {KIND}, {SERVICE}, and {SEQ:03}.': 'Available tokens: {PREFIX}, {FLOOR}, {KIND}, {SERVICE}, and {SEQ:03}.', 'Short prefix used in generated route names for this service.': 'Short prefix used in generated route names for this service.',
  'Minimize overlap with existing routes': 'Minimize overlap with existing routes', 'Turn penalty': 'Turn penalty', 'Ceiling route offset': 'Ceiling route offset', 'Overlap avoidance tier list': 'Overlap avoidance tier list',
  'Drafting': 'Drafting', 'Grid size': 'Grid size', 'Snap to grid': 'Snap to grid', 'Snap to wall endpoints': 'Snap to wall endpoints', 'Snap to walls and endpoints': 'Snap to walls and endpoints', 'Category colors': 'Category colors', 'Device defaults': 'Device defaults',
  'Color meaning legend': 'Color meaning legend', 'Identification meaning': 'Identification meaning', 'Required or reserved': 'Required or reserved', 'Standard wiring convention': 'Standard wiring convention', 'Project visual convention': 'Project visual convention', 'User-defined': 'User-defined',
  'Yellow-green is reserved for protective earth; blue identifies neutral.': 'Yellow-green is reserved for protective earth; blue identifies neutral.', 'Brown, black, and grey identify live or switched conductors.': 'Brown, black, and grey identify live or switched conductors.', 'Device and route display colors are editable; labels and patterns remain authoritative.': 'Device and route display colors are editable; labels and patterns remain authoritative.',
  'Choose first endpoint port': 'Choose first endpoint port', 'Choose second endpoint port': 'Choose second endpoint port', 'The first port direction is ignored; the second endpoint determines route flow.': 'The first port direction is ignored; the second endpoint determines route flow.', 'Input flows toward this device, output flows away, and bidirectional has no arrow.': 'Input flows toward this device, output flows away, and bidirectional has no arrow.',
  'Protective earth only': 'Protective earth only', 'Neutral conductor': 'Neutral conductor', 'Phase conductors': 'Phase conductors', 'Ethernet jacket': 'Ethernet jacket', 'Conduits and route display': 'Conduits and route display', 'Done': 'Done',
  'Properties': 'Properties', 'Nothing selected': 'Nothing selected', 'Select an object': 'Select an object', 'Locked': 'Locked', 'Unlocked': 'Unlocked', 'Duplicate': 'Duplicate', 'Delete': 'Delete',
  'Wall geometry': 'Wall geometry', 'Name': 'Name', 'Show': 'Show', 'Exact length': 'Exact length', 'Height': 'Height', 'Thickness': 'Thickness', 'Start X': 'Start X', 'Start Y': 'Start Y', 'End X': 'End X', 'End Y': 'End Y',
  'Open wall scheme': 'Open wall scheme', 'Description': 'Description', 'Floor area': 'Floor area', 'Associated walls': 'Associated walls', 'Device identity': 'Device identity', 'Manufacturer': 'Manufacturer', 'Model': 'Model',
  'Placement': 'Placement', 'Association': 'Association', 'Rotation Z': 'Rotation Z', 'Width': 'Width', 'Height size': 'Height size', 'Depth': 'Depth', 'Along wall': 'Along wall', 'Depth in wall': 'Depth in wall', 'Wall side': 'Wall side',
  'Power & network': 'Power & network', 'Power requirements': 'Power requirements', 'Voltage': 'Voltage', 'Current': 'Current', 'Power': 'Power', 'Network': 'Network', 'Status': 'Status', 'Installation date': 'Installation date', 'Notes': 'Notes',
  'Connection points': 'Connection points', '+ Port': '+ Port', 'No ports yet.': 'No ports yet.', 'Port type': 'Port type', 'Connector': 'Connector', 'Direction': 'Direction', 'Remove': 'Remove',
  'Visual identification': 'Visual identification', 'Functional color': 'Functional color', 'Physical product color': 'Physical product color', 'Display color': 'Display color', 'Color meaning': 'Color meaning',
  'Flow direction': 'Flow direction', 'Calculated geometric length': 'Calculated geometric length', 'Installed length': 'Installed length', 'Spare length': 'Spare length', 'Endpoints': 'Endpoints', 'Source device': 'Source device', 'Destination device': 'Destination device',
  'Electrical conductor identification': 'Electrical conductor identification', 'Single-phase residential': 'Single-phase residential', 'Three-phase': 'Three-phase', 'Ethernet termination': 'Ethernet termination', 'Conduit metadata': 'Conduit metadata',
  'Installation & test': 'Installation & test', 'Installation status': 'Installation status', 'Installation method': 'Installation method', 'Test status': 'Test status', 'Test date': 'Test date', 'Turning points (m)': 'Turning points (m)', 'Square route': 'Square route',
  'Custom properties': 'Custom properties', '+ Field': '+ Field', 'No custom fields.': 'No custom fields.', 'Annotation': 'Annotation', 'Text': 'Text',
  'Create custom device type': 'Create custom device type', 'Category': 'Category', 'Shape': 'Shape', 'Box': 'Box', 'Plate': 'Plate', 'Cylinder': 'Cylinder', 'Camera': 'Camera', 'Preview': 'Preview', 'Create device type': 'Create device type', 'Cancel': 'Cancel',
  'Local projects': 'Local projects', 'Create another project': 'Create another project', 'Each project has an isolated local workspace folder': 'Each project has an isolated local workspace folder', 'Updated': 'Updated', 'Current project': 'Current project', 'Open': 'Open', 'Tool': 'Tool', 'Grid': 'Grid', 'Snapping': 'Snapping',
  'Electrical power': 'Electrical power', 'Ethernet & data': 'Ethernet & data', 'Security': 'Security', 'HVAC': 'HVAC', 'Heating': 'Heating', 'Plumbing': 'Plumbing', 'Sensors': 'Sensors', 'Automation': 'Automation', 'Technical storage': 'Technical storage', 'Floor transitions': 'Floor transitions', 'Generic': 'Generic',
  'Power outlet': 'Power outlet', 'Junction box': 'Junction box', 'Electrical panel': 'Electrical panel', 'Switch': 'Switch', 'Light point': 'Light point', 'Ethernet outlet': 'Ethernet outlet', 'Patch panel': 'Patch panel', 'Network switch': 'Network switch', 'Router': 'Router', 'Wi-Fi access point': 'Wi-Fi access point', 'Rack': 'Rack', 'Server': 'Server', 'NAS': 'NAS',
  'Security camera': 'Security camera', 'Motion sensor': 'Motion sensor', 'Smoke detector': 'Smoke detector', 'Carbon monoxide detector': 'Carbon monoxide detector', 'Water leak sensor': 'Water leak sensor', 'Thermostat': 'Thermostat', 'Air vent': 'Air vent', 'Boiler': 'Boiler', 'Heat pump': 'Heat pump', 'Radiator': 'Radiator',
  'Water inlet': 'Water inlet', 'Water outlet': 'Water outlet', 'Valve': 'Valve', 'Pump': 'Pump', 'Drain point': 'Drain point', 'Relay': 'Relay', 'Smart switch': 'Smart switch', 'Automation controller': 'Automation controller', 'Gateway': 'Gateway',
  'Potable water tank': 'Potable water tank', 'Rainwater tank': 'Rainwater tank', 'External sewage tank': 'External sewage tank', 'Hot-water storage tank': 'Hot-water storage tank', 'Solar battery storage': 'Solar battery storage', 'Custom technical container': 'Custom technical container',
  'Door opening': 'Door opening', 'Window opening': 'Window opening', 'Furniture': 'Furniture', 'Route junction': 'Route junction',
  'Whole-house MEP report': 'Whole-house MEP report', 'Infrastructure overview': 'Infrastructure overview', 'Live totals from the locally saved project.': 'Live totals from the locally saved project.', 'Project totals': 'Project totals',
  'House model': 'House model', 'floors': 'floors', 'rooms': 'rooms', 'walls': 'walls', 'Wall network': 'Wall network', 'Total modelled wall length': 'Total modelled wall length', 'Technical devices': 'Technical devices', 'installed or tested': 'installed or tested', 'Technical routes': 'Technical routes', 'geometric length': 'geometric length',
  'Verification': 'Verification', 'Routes with a recorded test state': 'Routes with a recorded test state', 'Documentation': 'Documentation', 'Visible measurements': 'Visible measurements', 'Service distribution': 'Service distribution', 'Route length by service': 'Route length by service', 'Show all': 'Show all', 'Filter report to': 'Filter report to', 'devices': 'devices', 'routes': 'routes',
  'Add technical devices and routes to populate this report.': 'Add technical devices and routes to populate this report.', 'Route inventory': 'Route inventory', 'Length by route type': 'Length by route type', 'cable': 'cable', 'pipe': 'pipe', 'duct': 'duct', 'Level distribution': 'Level distribution', 'Inventory by floor': 'Inventory by floor', 'elevation': 'elevation',
  'Filtered detail': 'Filtered detail', 'All MEP assets': 'All MEP assets', 'Asset': 'Asset', 'Devices and routes': 'Devices and routes', 'Devices only': 'Devices only', 'Routes only': 'Routes only', 'Service category': 'Service category', 'All services': 'All services', 'All statuses': 'All statuses', 'Floor': 'Floor', 'All floors': 'All floors', 'Devices': 'Devices', 'Routes': 'Routes',
  'planned': 'planned', 'installed': 'installed', 'tested': 'tested', 'decommissioned': 'decommissioned', 'not tested': 'not tested', 'No matching devices.': 'No matching devices.', 'No matching routes.': 'No matching routes.',
  'Wall scheme export': 'Wall scheme export', 'Wall scheme': 'Wall scheme', 'Orthographic technical scheme · A4 landscape · generated locally': 'Orthographic technical scheme · A4 landscape · generated locally', 'Close dialog': 'Close dialog', 'Export scope': 'Export scope', 'Walls': 'Walls', 'Image': 'Image', 'Reset to A4 landscape': 'Reset to A4 landscape', 'Resolution scale': 'Resolution scale', 'print': 'print', 'Style': 'Style', 'Light': 'Light', 'Dark': 'Dark',
  'Content': 'Content', 'Transparent background': 'Transparent background', 'Wall outline': 'Wall outline', 'Dimensions': 'Dimensions', 'Labels': 'Labels', 'Route metadata': 'Route metadata', 'Legend': 'Legend', 'Title block': 'Title block', 'Room name': 'Room name', 'Wall name': 'Wall name', 'Export date': 'Export date', 'No wall available': 'No wall available', 'Draw or select a wall first.': 'Draw or select a wall first.', 'file will be generated': 'file will be generated', 'files will be generated': 'files will be generated', 'Generating…': 'Generating…', 'Export PNG': 'Export PNG',
  'Current 3D view': 'Current 3D view', 'low-ink light scheme': 'low-ink light scheme', 'Current view image export': 'Current view image export', 'Current view image': 'Current view image', 'Light, low-ink A4 layout · generated locally': 'Light, low-ink A4 layout · generated locally', 'Print layout': 'Print layout', 'landscape': 'landscape', 'The 3D scene is captured in light mode, placed on white paper, and uses no decorative background to reduce ink use.': 'The 3D scene is captured in light mode, placed on white paper, and uses no decorative background to reduce ink use.', 'Save PNG': 'Save PNG',
  'Open or manage projects': 'Open or manage projects', 'Save now (Ctrl+S)': 'Save now (Ctrl+S)', 'Undo (Ctrl+Z)': 'Undo (Ctrl+Z)', 'Redo (Ctrl+Y)': 'Redo (Ctrl+Y)', 'Toggle X-ray (X): make walls transparent and reveal services': 'Toggle X-ray (X): make walls transparent and reveal services', 'Opaque walls and standard depth': 'Opaque walls and standard depth', 'Reveal concealed services': 'Reveal concealed services', 'Show the selected room only': 'Show the selected room only', 'Show the selected wall only': 'Show the selected wall only', 'Toggle perspective / orthographic': 'Toggle perspective / orthographic', 'Plan view': 'Plan view', 'Reset camera': 'Reset camera', 'Orthographic technical PNG': 'Orthographic technical PNG', 'One PNG per selected wall': 'One PNG per selected wall', 'Validated local JSON': 'Validated local JSON', 'Restore a local JSON backup': 'Restore a local JSON backup', 'Theme': 'Theme', 'Light theme': 'Light theme', 'Use system theme': 'Use system theme', 'Dark theme': 'Dark theme', 'Filter device category': 'Filter device category', 'All categories': 'All categories', 'Filter devices': 'Filter devices', 'Filter devices…': 'Filter devices…', 'Route direction motion': 'Route direction motion', 'System': 'System', 'Animated': 'Animated', 'Reduced': 'Reduced', 'Uses your operating system motion preference.': 'Uses your operating system motion preference.', 'Direction arrows always move.': 'Direction arrows always move.', 'Direction arrows remain stationary.': 'Direction arrows remain stationary.',
  'Light switch': 'Light switch', 'TV antenna': 'TV antenna', 'FWA antenna': 'FWA antenna', 'Transformer': 'Transformer', 'Power supply': 'Power supply', 'UPS': 'UPS', 'Solar panel': 'Solar panel', 'Appliance connection': 'Appliance connection', 'Fibre termination': 'Fibre termination', 'Custom network device': 'Custom network device', 'Door sensor': 'Door sensor', 'Alarm siren': 'Alarm siren', 'Alarm control panel': 'Alarm control panel', 'Intercom': 'Intercom', 'Video intercom': 'Video intercom', 'Multi-detector': 'Multi-detector', 'Custom security device': 'Custom security device',
  'Indoor HVAC unit': 'Indoor HVAC unit', 'Outdoor unit': 'Outdoor unit', 'Temperature sensor': 'Temperature sensor', 'Duct endpoint': 'Duct endpoint', 'HVAC manifold': 'HVAC manifold', 'Underfloor heating connection': 'Underfloor heating connection', 'Custom HVAC device': 'Custom HVAC device', 'Plumbing manifold': 'Plumbing manifold', 'Hot-water connection': 'Hot-water connection', 'Cold-water connection': 'Cold-water connection', 'Custom plumbing device': 'Custom plumbing device', 'Smart sensor': 'Smart sensor', 'Motor controller': 'Motor controller', 'Custom automation device': 'Custom automation device',
  'Staircase': 'Staircase', 'Washing machine': 'Washing machine', 'Fridge': 'Fridge', 'Sink': 'Sink', 'Dishwasher': 'Dishwasher', 'Oven': 'Oven', 'Kitchen hood': 'Kitchen hood', 'Cabinet': 'Cabinet', 'Television': 'Television', 'Media console': 'Media console', 'Desktop PC': 'Desktop PC', 'Desk': 'Desk', 'Custom furniture': 'Custom furniture', 'Floor transition': 'Floor transition', 'Generic electronic device': 'Generic electronic device', 'Generic powered device': 'Generic powered device', 'Generic passive device': 'Generic passive device', 'Custom device': 'Custom device',
  'Overview sections': 'Overview sections', 'Lighting manager': 'Lighting manager', 'Rooms & zones': 'Rooms & zones', 'Asset inventory': 'Asset inventory', 'Electrical lighting': 'Electrical lighting', 'switches': 'switches', 'light points': 'light points', 'Add at least one light switch and one light point to build lighting controls.': 'Add at least one light switch and one light point to build lighting controls.', 'connected routes': 'connected routes', 'OFF': 'OFF', 'ON': 'ON', 'wired route found': 'wired route found', 'assignment only': 'assignment only', 'Circuit, relay, or installation notes': 'Circuit, relay, or installation notes', 'ON and OFF are documentation states only; the editor does not operate live electrical equipment.': 'ON and OFF are documentation states only; the editor does not operate live electrical equipment.', 'lighting control': 'lighting control',
  'House organization': 'House organization', 'Rooms, zones & assigned services': 'Rooms, zones & assigned services', 'Room category': 'Room category', 'No devices assigned.': 'No devices assigned.', 'Create rooms in the editor to organize the technical inventory here.': 'Create rooms in the editor to organize the technical inventory here.',
  'Project diagnostics': 'Project diagnostics', 'Review route clearances, cable lengths, riser continuity, and unconnected devices.': 'Review route clearances, cable lengths, riser continuity, and unconnected devices.', 'Check route intersections while modelling': 'Check route intersections while modelling', 'Route conflicts': 'Route conflicts', 'Review': 'Review', 'Long cable runs': 'Long cable runs', 'Riser issues': 'Riser issues', 'Unconnected devices': 'Unconnected devices', 'Route clearance': 'Route clearance', 'No route intersections or below-clearance approaches detected.': 'No route intersections or below-clearance approaches detected.', 'Severity': 'Severity', 'Cable run length': 'Cable run length', 'Every cable run is within the 10 m target plus 1 m tolerance.': 'Every cable run is within the 10 m target plus 1 m tolerance.', 'maximum accepted length': 'maximum accepted length', 'Locate': 'Locate', 'Vertical service risers': 'Vertical service risers', 'Every connected riser route is paired and directionally balanced.': 'Every connected riser route is paired and directionally balanced.', 'Devices without route attachments': 'Devices without route attachments', 'Every technical device has at least one route connection.': 'Every technical device has at least one route connection.',
  'Photo': 'Photo', 'Manage levels': 'Manage levels', 'Photo points': 'Photo points', 'Click the model to place': 'Click the model to place', 'Add photo point': 'Add photo point', 'New photo category': 'New photo category', 'Photo filters': 'Photo filters', 'Hide all': 'Hide all', 'Finished house': 'Finished house', 'Cable systems': 'Cable systems', 'Structural': 'Structural', 'Electrical': 'Electrical', 'Other': 'Other', 'Open attached photos': 'Open attached photos', 'Open photos': 'Open photos', 'Photo point': 'Photo point', 'Only JPEG, PNG, and WebP images are supported.': 'Only JPEG, PNG, and WebP images are supported.', 'Photos saved in the local project folder.': 'Photos saved in the local project folder.', 'Photo upload failed.': 'Photo upload failed.', 'Saving photos…': 'Saving photos…', 'Add pictures': 'Add pictures', 'Delete photo point': 'Delete photo point', 'Delete picture': 'Delete picture', 'No pictures attached': 'No pictures attached', 'Add one or more local images to this point.': 'Add one or more local images to this point.', 'Photo point placed. Add one or more local pictures.': 'Photo point placed. Add one or more local pictures.', 'Delete this photo point and its local pictures?': 'Delete this photo point and its local pictures?', 'One PNG per parete selezionata': 'One PNG per selected wall'
  , 'Appearance': 'Appearance'
  , 'Project-specific technical modelling rules.': 'Project-specific technical modelling rules.', 'Close settings': 'Close settings', 'Settings sections': 'Settings sections', 'Clearance, priorities, motion': 'Clearance, priorities, motion', 'Grid and snapping': 'Grid and snapping', 'Category identification': 'Category identification', 'Sizes, mounting backs, ports': 'Sizes, mounting backs, ports', 'issue found': 'issue found', 'issues found': 'issues found', 'Metric grid, snapping, and predictable route motion.': 'Metric grid, snapping, and predictable route motion.', 'Project conventions remain backed by text labels and route patterns.': 'Project conventions remain backed by text labels and route patterns.', 'Define installed sizes, mounting backs, connection holes, and complete rack systems.': 'Define installed sizes, mounting backs, connection holes, and complete rack systems.', 'Keep services orthogonal, separated, and inside approved building surfaces.': 'Keep services orthogonal, separated, and inside approved building surfaces.', 'Structural core': 'Structural core', 'Drywall left': 'Drywall left', 'Drywall right': 'Drywall right', 'Finished total': 'Finished total', 'Depth from wall': 'Depth from wall', 'Drywall lining': 'Drywall lining', 'Finished lined wall faces': 'Finished lined wall faces', 'Panel continuity': 'Panel continuity', 'Panel and junction continuity': 'Panel and junction continuity', 'Every panel and junction route has an explicit incoming-to-outgoing correspondence.': 'Every panel and junction route has an explicit incoming-to-outgoing correspondence.', 'Installation': 'Installation', 'Testing': 'Testing', 'No port assigned': 'No port assigned', 'Click to cycle route flow direction': 'Click to cycle route flow direction', 'Route category parameters': 'Route category parameters', 'Minimum separation': 'Minimum separation', 'Default route diameter': 'Default route diameter', 'Installed outside diameter used when a route has no explicit physical size.': 'Installed outside diameter used when a route has no explicit physical size.', 'No rooms on this level.': 'No rooms on this level.'
  , 'Light view': 'Light', 'Lighting view always uses X-ray.': 'Lighting view always uses X-ray.', 'Lighting continuity': 'Lighting continuity', 'selected level': 'selected level', 'Light points': 'Light points', 'Light switches': 'Light switches', 'Connection issues': 'Connection issues', 'Connection audit': 'Connection audit', 'No lighting wiring issues on this level.': 'No lighting wiring issues on this level.', 'Cable continuity': 'Cable continuity', 'Select a light point to identify every switch with documented cable continuity.': 'Select a light point to identify every switch with documented cable continuity.', 'controlling switch': 'controlling switch', 'controlling switches': 'controlling switches', 'No controlling switch': 'No controlling switch', 'No light points on this level.': 'No light points on this level.', 'Controlling switches blink red in the 3D view.': 'Controlling switches blink red in the 3D view.', 'No complete switch-to-light cable path is documented.': 'No complete switch-to-light cable path is documented.', 'Saved locally': 'Saved locally', 'Autosave is not working. Click to retry.': 'Autosave is not working. Click to retry.', 'Unsaved changes are being stored locally.': 'Unsaved changes are being stored locally.', 'Autosave error': 'Autosave error', 'Saving locally': 'Saving locally'
  , 'Review physical clearances, coordinated route layouts, cable lengths, continuity, and unconnected devices.': 'Review physical clearances, coordinated route layouts, cable lengths, continuity, and unconnected devices.'
  , 'Route layout and clearance': 'Route layout and clearance', 'No physical conflicts or coordinated layout improvements detected.': 'No physical conflicts or coordinated layout improvements detected.'
  , 'Coordinate': 'Coordinate', 'fewer turns': 'fewer turns', 'conflicts removed': 'conflicts removed', 'Review model': 'Review model'
  , 'No coordinated route improvements are available.': 'No coordinated route improvements are available.', 'Coordinated route layout': 'Coordinated route layout', 'Coordinated route layout applied.': 'Coordinated route layout applied.'
  , 'Coordinated route layout review': 'Coordinated route layout review', 'Layout proposal': 'Layout proposal', 'Close route layout review': 'Close route layout review'
  , 'Coordinated proposal in model': 'Coordinated proposal in model', 'Current route layout in model': 'Current route layout in model', 'The complete affected route set is previewed and applied together.': 'The complete affected route set is previewed and applied together.'
  , 'Current turns': 'Current turns', 'Proposed turns': 'Proposed turns', 'Fewer turns': 'Fewer turns', 'Conflicts removed': 'Conflicts removed', 'Length change': 'Length change', 'routes coordinated on this floor': 'routes coordinated on this floor'
  , 'Show original': 'Show original', 'Show coordinated solution': 'Show coordinated solution', 'Skip / next': 'Skip / next', 'Apply all routes': 'Apply all routes', 'Route conflict': 'Route conflict'
  , 'Administration': 'Administration', 'Local application branding and privacy': 'Local application branding and privacy', 'Application-wide local settings that are never stored in project backups.': 'Application-wide local settings that are never stored in project backups.'
  , 'Application icon': 'Application icon', 'The public source and installer always use the neutral icon. A private replacement is stored only in this local browser or desktop profile.': 'The public source and installer always use the neutral icon. A private replacement is stored only in this local browser or desktop profile.'
  , 'Choose local icon': 'Choose local icon', 'Use neutral icon': 'Use neutral icon', 'Choose a PNG, JPEG, or WebP image.': 'Choose a PNG, JPEG, or WebP image.', 'The application icon must be smaller than 4 MB.': 'The application icon must be smaller than 4 MB.', 'The application icon could not be read.': 'The application icon could not be read.', 'Unsupported application icon data.': 'Unsupported application icon data.'
};
