export const it: Record<string, string> = {
  'Infrastructure editor · Local only': 'Editor infrastrutture · Solo locale',
  'Editor': 'Editor', 'Overview': 'Riepilogo', 'Settings': 'Impostazioni', 'Projects': 'Progetti', 'Saved': 'Salvato', 'Saving…': 'Salvataggio…', 'Save error': 'Errore salvataggio',
  'X-ray': 'Raggi X', 'X-ray ON': 'Raggi X ATTIVI', 'Normal view': 'Vista normale', 'Inside walls': 'Dentro le pareti', 'Isolate room': 'Isola stanza', 'Isolate wall': 'Isola parete',
  'Perspective': 'Prospettiva', 'Orthographic': 'Ortogonale', 'Views': 'Viste', 'Top': 'Dall’alto', 'Isometric': 'Isometrica', 'Fit full house': 'Adatta casa completa', 'Fit selection': 'Adatta selezione', 'Export': 'Esporta',
  'Selected wall scheme': 'Schema parete selezionata', 'Batch wall schemes': 'Schemi pareti in serie', 'Project backup': 'Backup progetto', 'Import backup': 'Importa backup',
  'Active level': 'Livello attivo', 'Manage levels and blueprints': 'Gestisci livelli e planimetrie', 'Elevation': 'Quota', 'Ceiling height': 'Altezza soffitto', 'Full house': 'Casa completa', 'Adjacent blueprint': 'Pianta adiacente', 'Below': 'Sotto', 'Above': 'Sopra',
  'Create': 'Crea', 'Wall': 'Parete', 'Ceiling': 'Soffitto', 'Wall mounted': 'Montaggio a parete', 'Ceiling mounted': 'Montaggio a soffitto', 'Room': 'Stanza', 'Structure': 'Struttura', 'Device': 'Dispositivo', 'Route': 'Percorso', 'Container': 'Serbatoio', 'Measure': 'Misura', 'Select': 'Seleziona',
  'Room from selected walls': 'Stanza dalle pareti selezionate', 'New wall thickness': 'Spessore nuove pareti', 'House structure': 'Struttura casa', 'Column': 'Pilastro', 'Device catalogue': 'Catalogo dispositivi', '+ Custom': '+ Personalizzato',
  'Technical containers': 'Contenitori tecnici', 'Route setup': 'Impostazione percorso', 'Cable': 'Cavo', 'Pipe': 'Tubo', 'Duct': 'Condotto', 'Junction': 'Giunzione', 'Service': 'Servizio',
  'Measurement mode': 'Modalità misura', '3D distance': 'Distanza 3D', 'Vertical height': 'Altezza verticale', 'Services visibility': 'Visibilità servizi', 'All': 'Tutti', 'None': 'Nessuno', 'Rooms': 'Stanze', '+ Category': '+ Categoria',
  'No rooms defined.': 'Nessuna stanza definita.', 'Uncategorized': 'Senza categoria', 'Edit': 'Modifica', 'Custom': 'Personalizzato',
  'Choose any service-compatible first port. The second port will be limited to the coherent direction.': 'Scegli una prima porta compatibile con il servizio. La seconda sarà limitata alla direzione coerente.',
  'Only a port coherent with the first endpoint direction can finish this route.': 'Solo una porta coerente con la direzione del primo terminale può completare il percorso.',
  'Wrong direction': 'Direzione non coerente',
  'Add another port': 'Aggiungi un’altra porta', 'New input': 'Nuovo ingresso', 'New output': 'Nuova uscita', 'Automatically placed inside the enclosure; its size grows when required.': 'Posizionata automaticamente all’interno del contenitore; le dimensioni aumentano quando necessario.',
  'Editor settings': 'Impostazioni editor', 'Project-specific drafting, route-planning, and visual rules': 'Regole di disegno, instradamento e visualizzazione del progetto', 'Route planning': 'Pianificazione percorsi',
  'Organize path, separation, turn, and identification rules for technical routes.': 'Organizza percorso, separazione, curve e identificazione delle reti tecniche.',
  'Path rules': 'Regole del percorso', 'Avoid unrelated route conflicts': 'Evita conflitti tra percorsi non correlati', 'Strongly group routes sharing a destination': 'Raggruppa i percorsi con la stessa destinazione', 'Floor route offset': 'Offset percorso pavimento',
  'Floor service stack': 'Strati dei servizi a pavimento', 'Move deeper': 'Sposta più in profondità', 'Move closer to floor': 'Sposta verso il pavimento', 'Avoidance tiers': 'Priorità di protezione', 'Minimum side-by-side separation': 'Separazione laterale minima', 'Turn curvature': 'Curvatura delle svolte',
  'Route identification': 'Identificazione percorsi', 'Naming pattern': 'Schema di denominazione', 'Example': 'Esempio',
  'Routes inside walls use only wall-local horizontal and vertical runs. Floor and ceiling paths use the configured service bend radius.': 'I percorsi nelle pareti usano solo tratti orizzontali e verticali locali alla parete. Pavimenti e soffitti usano il raggio di curvatura configurato.',
  'Adds an equivalent distance cost to each turn so route choices favor fewer corners.': 'Aggiunge un costo equivalente a ogni svolta per favorire percorsi con meno angoli.', 'Negative values move the route inside and above the finished ceiling surface.': 'I valori negativi spostano il percorso all’interno, sopra la superficie finita del soffitto.', 'Sets the route reference plane below the finished floor surface.': 'Imposta il piano di riferimento del percorso sotto la superficie finita del pavimento.',
  'Order of concealed floor services from deepest to closest to the finished floor. Vertical placement uses each service minimum side-by-side separation.': 'Ordine dei servizi nascosti dal più profondo al più vicino al pavimento finito. Il posizionamento verticale usa la separazione laterale minima di ogni servizio.', 'Tier 1 receives the most protected path when services compete for space.': 'La priorità 1 riceve il percorso più protetto quando i servizi competono per lo spazio.', 'Set the conflict-avoidance priority for this service.': 'Imposta la priorità anti-conflitto per questo servizio.',
  'This value separates bundled routes laterally and also separates adjacent floor service tiers.': 'Questo valore separa lateralmente i percorsi raggruppati e anche gli strati adiacenti dei servizi a pavimento.', 'Minimum centerline separation for this service.': 'Separazione minima tra gli assi per questo servizio.', 'Floor and ceiling corners use the service bend radius. Transitions into walls are automatically reduced to stay inside the wall lining or structural core.': 'Le curve a pavimento e soffitto usano il raggio del servizio. Le transizioni verso le pareti vengono ridotte automaticamente per restare nel rivestimento o nel nucleo strutturale.', 'Preferred bend radius for this service on floor and ceiling paths.': 'Raggio di curvatura preferito per questo servizio sui percorsi a pavimento e soffitto.',
  'Route identifiers remain unique and documented; service prefixes are project conventions.': 'Gli identificatori restano univoci e documentati; i prefissi dei servizi sono convenzioni di progetto.', 'Available tokens: {PREFIX}, {FLOOR}, {KIND}, {SERVICE}, and {SEQ:03}.': 'Variabili disponibili: {PREFIX}, {FLOOR}, {KIND}, {SERVICE} e {SEQ:03}.', 'Short prefix used in generated route names for this service.': 'Prefisso breve usato nei nomi generati per questo servizio.',
  'Minimize overlap with existing routes': 'Riduci sovrapposizione con percorsi esistenti', 'Turn penalty': 'Penalità curve', 'Ceiling route offset': 'Offset percorso soffitto', 'Overlap avoidance tier list': 'Priorità anti-sovrapposizione',
  'Drafting': 'Disegno', 'Grid size': 'Passo griglia', 'Snap to grid': 'Aggancia alla griglia', 'Snap to wall endpoints': 'Aggancia agli estremi parete', 'Snap to walls and endpoints': 'Aggancia a pareti ed estremi', 'Snap to walls, corners and angles': 'Aggancia a pareti, angoli e direzioni', 'Corner snap': 'ANGOLO', 'Wall snap': 'PARETE', 'Grid snap': 'GRIGLIA', 'Perpendicular 90°': '90°', 'East / West axis': 'E–O', 'North / South axis': 'N–S', 'Category colors': 'Colori categorie', 'Device defaults': 'Valori predefiniti dispositivi',
  'Color meaning legend': 'Legenda significato colori', 'Identification meaning': 'Significato dell’identificazione', 'Required or reserved': 'Obbligatorio o riservato', 'Standard wiring convention': 'Convenzione standard di cablaggio', 'Project visual convention': 'Convenzione visiva del progetto', 'User-defined': 'Definito dall’utente',
  'Yellow-green is reserved for protective earth; blue identifies neutral.': 'Il giallo-verde è riservato al conduttore di protezione; il blu identifica il neutro.', 'Brown, black, and grey identify live or switched conductors.': 'Marrone, nero e grigio identificano i conduttori di fase o comandati.', 'Device and route display colors are editable; labels and patterns remain authoritative.': 'I colori visualizzati di dispositivi e percorsi sono modificabili; etichette e motivi restano il riferimento.',
  'Choose first endpoint port': 'Scegli la porta del primo estremo', 'Choose second endpoint port': 'Scegli la porta del secondo estremo', 'The first port direction is ignored; the second endpoint determines route flow.': 'La direzione della prima porta viene ignorata; il secondo estremo determina il flusso del percorso.', 'Input flows toward this device, output flows away, and bidirectional has no arrow.': 'Ingresso dirige il flusso verso il dispositivo, uscita in senso opposto; bidirezionale non mostra frecce.',
  'Protective earth only': 'Solo conduttore di protezione', 'Neutral conductor': 'Conduttore neutro', 'Phase conductors': 'Conduttori di fase', 'Ethernet jacket': 'Guaina Ethernet', 'Conduits and route display': 'Cavidotti e visualizzazione percorsi', 'Done': 'Fine',
  'Properties': 'Proprietà', 'Nothing selected': 'Nessuna selezione', 'Select an object': 'Seleziona un oggetto', 'Locked': 'Bloccato', 'Unlocked': 'Sbloccato', 'Duplicate': 'Duplica', 'Delete': 'Elimina',
  'Wall geometry': 'Geometria parete', 'Name': 'Nome', 'Show': 'Mostra', 'Exact length': 'Lunghezza esatta', 'Height': 'Altezza', 'Thickness': 'Spessore', 'Start X': 'Inizio X', 'Start Y': 'Inizio Y', 'End X': 'Fine X', 'End Y': 'Fine Y',
  'Open wall scheme': 'Apri schema parete', 'Description': 'Descrizione', 'Floor area': 'Superficie', 'Associated walls': 'Pareti associate', 'Device identity': 'Identità dispositivo', 'Manufacturer': 'Produttore', 'Model': 'Modello',
  'Placement': 'Posizionamento', 'Association': 'Associazione', 'Rotation Z': 'Rotazione Z', 'Width': 'Larghezza', 'Height size': 'Dimensione verticale', 'Depth': 'Profondità', 'Along wall': 'Lungo parete', 'Depth in wall': 'Profondità nella parete', 'Wall side': 'Lato parete',
  'Power & network': 'Alimentazione e rete', 'Power requirements': 'Requisiti alimentazione', 'Voltage': 'Tensione', 'Current': 'Corrente', 'Power': 'Potenza', 'Network': 'Rete', 'Status': 'Stato', 'Installation date': 'Data installazione', 'Notes': 'Note',
  'Connection points': 'Punti di connessione', '+ Port': '+ Porta', 'No ports yet.': 'Nessuna porta.', 'Port type': 'Tipo porta', 'Connector': 'Connettore', 'Direction': 'Direzione', 'Remove': 'Rimuovi',
  'Visual identification': 'Identificazione visiva', 'Functional color': 'Colore funzionale', 'Physical product color': 'Colore fisico prodotto', 'Display color': 'Colore visualizzato', 'Color meaning': 'Significato colore',
  'Flow direction': 'Direzione flusso', 'Calculated geometric length': 'Lunghezza geometrica calcolata', 'Installed length': 'Lunghezza installata', 'Spare length': 'Scorta', 'Endpoints': 'Estremi', 'Source device': 'Dispositivo sorgente', 'Destination device': 'Dispositivo destinazione',
  'Electrical conductor identification': 'Identificazione conduttori elettrici', 'Single-phase residential': 'Monofase residenziale', 'Three-phase': 'Trifase', 'Ethernet termination': 'Terminazione Ethernet', 'Conduit metadata': 'Dati cavidotto',
  'Installation & test': 'Installazione e test', 'Installation status': 'Stato installazione', 'Installation method': 'Metodo installazione', 'Test status': 'Stato test', 'Test date': 'Data test', 'Turning points (m)': 'Punti di svolta (m)', 'Square route': 'Squadra percorso',
  'Custom properties': 'Proprietà personalizzate', '+ Field': '+ Campo', 'No custom fields.': 'Nessun campo personalizzato.', 'Annotation': 'Annotazione', 'Text': 'Testo',
  'Create custom device type': 'Crea tipo dispositivo personalizzato', 'Category': 'Categoria', 'Shape': 'Forma', 'Box': 'Scatola', 'Plate': 'Placca', 'Cylinder': 'Cilindro', 'Camera': 'Telecamera', 'Preview': 'Anteprima', 'Create device type': 'Crea tipo dispositivo', 'Cancel': 'Annulla',
  'Local projects': 'Progetti locali', 'Create another project': 'Crea un altro progetto', 'Each project has an isolated local workspace folder': 'Ogni progetto ha una cartella di lavoro locale isolata', 'Updated': 'Aggiornato', 'Current project': 'Progetto corrente', 'Open': 'Apri', 'Tool': 'Strumento', 'Grid': 'Griglia', 'Snapping': 'Aggancio',
  'Electrical power': 'Energia elettrica', 'Ethernet & data': 'Ethernet e dati', 'Security': 'Sicurezza', 'HVAC': 'Climatizzazione', 'Heating': 'Riscaldamento', 'Plumbing': 'Idraulica', 'Sensors': 'Sensori', 'Automation': 'Automazione', 'Technical storage': 'Accumuli tecnici', 'Floor transitions': 'Passaggi tra piani', 'Generic': 'Generico',
  'Power outlet': 'Presa elettrica', 'Junction box': 'Scatola di derivazione', 'Electrical panel': 'Quadro elettrico', 'Switch': 'Interruttore', 'Light point': 'Punto luce', 'Ethernet outlet': 'Presa Ethernet', 'Patch panel': 'Patch panel', 'Network switch': 'Switch di rete', 'Router': 'Router', 'Wi-Fi access point': 'Access point Wi-Fi', 'Rack': 'Rack', 'Server': 'Server', 'NAS': 'NAS',
  'Security camera': 'Telecamera di sicurezza', 'Motion sensor': 'Sensore di movimento', 'Smoke detector': 'Rilevatore di fumo', 'Carbon monoxide detector': 'Rilevatore monossido di carbonio', 'Water leak sensor': 'Sensore perdita acqua', 'Thermostat': 'Termostato', 'Air vent': 'Bocchetta aria', 'Boiler': 'Caldaia', 'Heat pump': 'Pompa di calore', 'Radiator': 'Radiatore',
  'Water inlet': 'Ingresso acqua', 'Water outlet': 'Uscita acqua', 'Valve': 'Valvola', 'Pump': 'Pompa', 'Drain point': 'Punto scarico', 'Relay': 'Relè', 'Smart switch': 'Interruttore smart', 'Automation controller': 'Controller automazione', 'Gateway': 'Gateway',
  'Potable water tank': 'Serbatoio acqua potabile', 'Rainwater tank': 'Serbatoio acqua piovana', 'External sewage tank': 'Serbatoio fognario esterno', 'Hot-water storage tank': 'Accumulo acqua calda', 'Solar battery storage': 'Accumulo batterie solari', 'Custom technical container': 'Contenitore tecnico personalizzato',
  'Door opening': 'Apertura porta', 'Window opening': 'Apertura finestra', 'Furniture': 'Arredo', 'Route junction': 'Giunzione percorso',
  'Whole-house MEP report': 'Rapporto MEP dell’intera casa', 'Infrastructure overview': 'Riepilogo infrastrutture', 'Live totals from the locally saved project.': 'Totali aggiornati dal progetto salvato localmente.', 'Project totals': 'Totali progetto',
  'House model': 'Modello della casa', 'floors': 'piani', 'rooms': 'stanze', 'walls': 'pareti', 'Wall network': 'Rete di pareti', 'Total modelled wall length': 'Lunghezza totale pareti modellate', 'Technical devices': 'Dispositivi tecnici', 'installed or tested': 'installati o collaudati', 'Technical routes': 'Percorsi tecnici', 'geometric length': 'lunghezza geometrica',
  'Verification': 'Verifica', 'Routes with a recorded test state': 'Percorsi con stato di collaudo registrato', 'Documentation': 'Documentazione', 'Visible measurements': 'Misure visibili', 'Service distribution': 'Distribuzione servizi', 'Route length by service': 'Lunghezza percorsi per servizio', 'Show all': 'Mostra tutto', 'Filter report to': 'Filtra rapporto per', 'devices': 'dispositivi', 'routes': 'percorsi',
  'Add technical devices and routes to populate this report.': 'Aggiungi dispositivi e percorsi tecnici per popolare il rapporto.', 'Route inventory': 'Inventario percorsi', 'Length by route type': 'Lunghezza per tipo di percorso', 'cable': 'cavo', 'pipe': 'tubo', 'duct': 'condotto', 'Level distribution': 'Distribuzione livelli', 'Inventory by floor': 'Inventario per piano', 'elevation': 'quota',
  'Filtered detail': 'Dettaglio filtrato', 'All MEP assets': 'Tutti gli elementi MEP', 'Asset': 'Elemento', 'Devices and routes': 'Dispositivi e percorsi', 'Devices only': 'Solo dispositivi', 'Routes only': 'Solo percorsi', 'Service category': 'Categoria servizio', 'All services': 'Tutti i servizi', 'All statuses': 'Tutti gli stati', 'Floor': 'Piano', 'All floors': 'Tutti i piani', 'Devices': 'Dispositivi', 'Routes': 'Percorsi',
  'planned': 'pianificato', 'installed': 'installato', 'tested': 'collaudato', 'decommissioned': 'dismesso', 'not tested': 'non collaudato', 'No matching devices.': 'Nessun dispositivo corrispondente.', 'No matching routes.': 'Nessun percorso corrispondente.',
  'Wall scheme export': 'Esportazione schema parete', 'Wall scheme': 'Schema parete', 'Orthographic technical scheme · A4 landscape · generated locally': 'Schema tecnico ortogonale · A4 orizzontale · generato localmente', 'Close dialog': 'Chiudi finestra', 'Export scope': 'Ambito esportazione', 'Walls': 'Pareti', 'Image': 'Immagine', 'Reset to A4 landscape': 'Ripristina A4 orizzontale', 'Resolution scale': 'Scala risoluzione', 'print': 'stampa', 'Style': 'Stile', 'Light': 'Chiaro', 'Dark': 'Scuro',
  'Content': 'Contenuto', 'Transparent background': 'Sfondo trasparente', 'Wall outline': 'Contorno parete', 'Dimensions': 'Quote', 'Labels': 'Etichette', 'Route metadata': 'Metadati percorsi', 'Legend': 'Legenda', 'Title block': 'Cartiglio', 'Room name': 'Nome stanza', 'Wall name': 'Nome parete', 'Export date': 'Data esportazione', 'No wall available': 'Nessuna parete disponibile', 'Draw or select a wall first.': 'Disegna o seleziona prima una parete.', 'file will be generated': 'file verrà generato', 'files will be generated': 'file verranno generati', 'Generating…': 'Generazione…', 'Export PNG': 'Esporta PNG',
  'Current 3D view': 'Vista 3D corrente', 'low-ink light scheme': 'schema chiaro a basso consumo d’inchiostro', 'Current view image export': 'Esportazione immagine vista corrente', 'Current view image': 'Immagine vista corrente', 'Light, low-ink A4 layout · generated locally': 'Layout A4 chiaro a basso consumo d’inchiostro · generato localmente', 'Print layout': 'Layout di stampa', 'landscape': 'orizzontale', 'The 3D scene is captured in light mode, placed on white paper, and uses no decorative background to reduce ink use.': 'La scena 3D viene acquisita in modalità chiara, disposta su carta bianca e senza sfondo decorativo per ridurre il consumo d’inchiostro.', 'Save PNG': 'Salva PNG',
  'Open or manage projects': 'Apri o gestisci progetti', 'Save now (Ctrl+S)': 'Salva ora (Ctrl+S)', 'Undo (Ctrl+Z)': 'Annulla (Ctrl+Z)', 'Redo (Ctrl+Y)': 'Ripeti (Ctrl+Y)', 'Toggle X-ray (X): make walls transparent and reveal services': 'Attiva/disattiva raggi X (X): rende trasparenti le pareti e mostra i servizi', 'Opaque walls and standard depth': 'Pareti opache e profondità normale', 'Reveal concealed services': 'Mostra i servizi nascosti', 'Show the selected room only': 'Mostra solo la stanza selezionata', 'Show the selected wall only': 'Mostra solo la parete selezionata', 'Toggle perspective / orthographic': 'Alterna prospettiva e ortogonale', 'Plan view': 'Vista in pianta', 'Reset camera': 'Ripristina telecamera', 'Orthographic technical PNG': 'PNG tecnico ortogonale', 'One PNG per parete selezionata': 'Un PNG per parete selezionata', 'Validated local JSON': 'JSON locale convalidato', 'Restore a local JSON backup': 'Ripristina un backup JSON locale', 'Theme': 'Tema', 'Light theme': 'Tema chiaro', 'Use system theme': 'Usa tema di sistema', 'Dark theme': 'Tema scuro', 'Open documentation': 'Apri documentazione', 'Filter device category': 'Filtra categoria dispositivi', 'All categories': 'Tutte le categorie', 'Filter devices': 'Filtra dispositivi', 'Filter devices…': 'Filtra dispositivi…', 'Route direction motion': 'Movimento direzione percorsi', 'System': 'Sistema', 'Animated': 'Animato', 'Reduced': 'Ridotto', 'Uses your operating system motion preference.': 'Usa la preferenza di movimento del sistema operativo.', 'Direction arrows always move.': 'Le frecce direzionali si muovono sempre.', 'Direction arrows remain stationary.': 'Le frecce direzionali restano ferme.',
  'Light switch': 'Interruttore luce', 'TV antenna': 'Antenna TV', 'FWA antenna': 'Antenna FWA', 'Transformer': 'Trasformatore', 'Power supply': 'Alimentatore', 'UPS': 'UPS', 'Solar panel': 'Pannello solare', 'Appliance connection': 'Collegamento elettrodomestico', 'Fibre termination': 'Terminazione fibra', 'Custom network device': 'Dispositivo di rete personalizzato', 'Door sensor': 'Sensore porta', 'Alarm siren': 'Sirena allarme', 'Alarm control panel': 'Centrale allarme', 'Intercom': 'Citofono', 'Video intercom': 'Videocitofono', 'Multi-detector': 'Rilevatore multiplo', 'Custom security device': 'Dispositivo di sicurezza personalizzato',
  'Indoor HVAC unit': 'Unità interna climatizzazione', 'Outdoor unit': 'Unità esterna', 'Temperature sensor': 'Sensore temperatura', 'Duct endpoint': 'Terminale condotto', 'HVAC manifold': 'Collettore climatizzazione', 'Underfloor heating connection': 'Collegamento riscaldamento a pavimento', 'Custom HVAC device': 'Dispositivo HVAC personalizzato', 'Plumbing manifold': 'Collettore idraulico', 'Hot-water connection': 'Collegamento acqua calda', 'Cold-water connection': 'Collegamento acqua fredda', 'Custom plumbing device': 'Dispositivo idraulico personalizzato', 'Smart sensor': 'Sensore smart', 'Motor controller': 'Controller motore', 'Custom automation device': 'Dispositivo automazione personalizzato',
  'Staircase': 'Scala', 'Washing machine': 'Lavatrice', 'Fridge': 'Frigorifero', 'Sink': 'Lavello', 'Dishwasher': 'Lavastoviglie', 'Oven': 'Forno', 'Kitchen hood': 'Cappa cucina', 'Cabinet': 'Mobile', 'Television': 'Televisore', 'Media console': 'Mobile multimediale', 'Desktop PC': 'PC desktop', 'Desk': 'Scrivania', 'Custom furniture': 'Arredo personalizzato', 'Floor transition': 'Passaggio tra piani', 'Generic electronic device': 'Dispositivo elettronico generico', 'Generic powered device': 'Dispositivo alimentato generico', 'Generic passive device': 'Dispositivo passivo generico', 'Custom device': 'Dispositivo personalizzato',
  'Overview sections': 'Sezioni riepilogo', 'Lighting manager': 'Gestione illuminazione', 'Rooms & zones': 'Stanze e zone', 'Asset inventory': 'Inventario elementi', 'Electrical lighting': 'Illuminazione elettrica', 'switches': 'interruttori', 'light points': 'punti luce', 'Add at least one light switch and one light point to build lighting controls.': 'Aggiungi almeno un interruttore luce e un punto luce per creare i comandi di illuminazione.', 'connected routes': 'percorsi collegati', 'OFF': 'SPENTO', 'ON': 'ACCESO', 'wired route found': 'percorso cablato trovato', 'assignment only': 'solo assegnazione', 'Circuit, relay, or installation notes': 'Note su circuito, relè o installazione', 'ON and OFF are documentation states only; the editor does not operate live electrical equipment.': 'ACCESO e SPENTO sono stati documentali: l’editor non comanda impianti elettrici reali.', 'lighting control': 'comando illuminazione',
  'House organization': 'Organizzazione casa', 'Rooms, zones & assigned services': 'Stanze, zone e servizi assegnati', 'Room category': 'Categoria stanza', 'No devices assigned.': 'Nessun dispositivo assegnato.', 'Create rooms in the editor to organize the technical inventory here.': 'Crea le stanze nell’editor per organizzare qui l’inventario tecnico.',
  'Project diagnostics': 'Diagnostica progetto', 'Review route clearances, cable lengths, riser continuity, and unconnected devices.': 'Controlla distanze dei percorsi, lunghezze dei cavi, continuità dei montanti e dispositivi non collegati.', 'Check route intersections while modelling': 'Controlla le intersezioni durante la modellazione', 'Route conflicts': 'Conflitti percorsi', 'Review': 'Controlla', 'Long cable runs': 'Tratte cavo lunghe', 'Riser issues': 'Problemi montanti', 'Unconnected devices': 'Dispositivi non collegati', 'Route clearance': 'Distanza tra percorsi', 'No route intersections or below-clearance approaches detected.': 'Nessuna intersezione o distanza insufficiente rilevata.', 'Severity': 'Gravità', 'Cable run length': 'Lunghezza tratta cavo', 'Every cable run is within the 10 m target plus 1 m tolerance.': 'Ogni tratta cavo rispetta il limite di 10 m più 1 m di tolleranza.', 'maximum accepted length': 'lunghezza massima accettata', 'Locate': 'Individua', 'Vertical service risers': 'Montanti tecnici verticali', 'Every connected riser route is paired and directionally balanced.': 'Ogni percorso nel montante è abbinato e bilanciato per direzione.', 'Devices without route attachments': 'Dispositivi senza percorsi collegati', 'Every technical device has at least one route connection.': 'Ogni dispositivo tecnico ha almeno un percorso collegato.',
  'Photo': 'Foto', 'Manage levels': 'Gestisci livelli', 'Photo points': 'Punti foto', 'Click the model to place': 'Fai clic sul modello per posizionare', 'Add photo point': 'Aggiungi punto foto', 'New photo category': 'Categoria nuova foto', 'Photo filters': 'Filtri foto', 'Hide all': 'Nascondi tutto', 'Finished house': 'Casa finita', 'Cable systems': 'Sistemi di cablaggio', 'Structural': 'Strutturale', 'Electrical': 'Elettrico', 'Other': 'Altro', 'Open attached photos': 'Apri foto allegate', 'Open photos': 'Apri foto', 'Photo point': 'Punto foto', 'Only JPEG, PNG, and WebP images are supported.': 'Sono supportate solo immagini JPEG, PNG e WebP.', 'Photos saved in the local project folder.': 'Foto salvate nella cartella locale del progetto.', 'Photo upload failed.': 'Salvataggio foto non riuscito.', 'Saving photos…': 'Salvataggio foto…', 'Add pictures': 'Aggiungi immagini', 'Delete photo point': 'Elimina punto foto', 'Delete picture': 'Elimina immagine', 'No pictures attached': 'Nessuna immagine allegata', 'Add one or more local images to this point.': 'Aggiungi una o più immagini locali a questo punto.', 'Photo point placed. Add one or more local pictures.': 'Punto foto posizionato. Aggiungi una o più immagini locali.', 'Delete this photo point and its local pictures?': 'Eliminare questo punto foto e le sue immagini locali?', 'One PNG per selected wall': 'Un PNG per parete selezionata'
  , 'Appearance': 'Aspetto'
  , 'Project-specific technical modelling rules.': 'Regole tecniche specifiche del progetto.', 'Close settings': 'Chiudi impostazioni', 'Settings sections': 'Sezioni impostazioni', 'Clearance, priorities, motion': 'Distanze, priorità e movimento', 'Grid and snapping': 'Griglia e aggancio', 'Category identification': 'Identificazione categorie', 'Sizes, mounting backs, ports': 'Dimensioni, superfici posteriori e porte', 'issue found': 'problema trovato', 'issues found': 'problemi trovati', 'Metric grid, snapping, and predictable route motion.': 'Griglia metrica, aggancio e movimento prevedibile dei percorsi.', 'Project conventions remain backed by text labels and route patterns.': 'Le convenzioni del progetto sono supportate da etichette e motivi dei percorsi.', 'Define installed sizes, mounting backs, connection holes, and complete rack systems.': 'Definisci dimensioni installate, superfici posteriori, connessioni e sistemi rack completi.', 'Keep services orthogonal, separated, and inside approved building surfaces.': 'Mantieni i servizi ortogonali, separati e nelle superfici edilizie consentite.', 'Structural core': 'Nucleo strutturale', 'Drywall left': 'Cartongesso sinistro', 'Drywall right': 'Cartongesso destro', 'Finished total': 'Totale finito', 'Depth from wall': 'Profondità dalla parete', 'Drywall lining': 'Rivestimento in cartongesso', 'Finished lined wall faces': 'Superfici finite rivestite', 'Panel continuity': 'Continuità quadri', 'Panel and junction continuity': 'Continuità di quadri e cassette', 'Every panel and junction route has an explicit incoming-to-outgoing correspondence.': 'Ogni percorso di quadri e cassette ha una corrispondenza esplicita tra ingresso e uscita.', 'Installation': 'Installazione', 'Testing': 'Collaudo', 'No port assigned': 'Nessuna porta assegnata', 'Click to cycle route flow direction': 'Fai clic per cambiare la direzione del flusso', 'Route category parameters': 'Parametri delle categorie di percorso', 'Minimum separation': 'Distanza minima', 'Default route diameter': 'Diametro predefinito del percorso', 'Installed outside diameter used when a route has no explicit physical size.': 'Diametro esterno installato usato quando un percorso non ha una dimensione fisica esplicita.', 'No rooms on this level.': 'Nessuna stanza su questo livello.'
  , 'Light view': 'Luci', 'Lighting view always uses X-ray.': 'La vista luci usa sempre i raggi X.', 'Lighting continuity': 'Continuità illuminazione', 'selected level': 'livello selezionato', 'Light points': 'Punti luce', 'Light switches': 'Interruttori luce', 'Connection issues': 'Problemi di collegamento', 'Connection audit': 'Verifica collegamenti', 'No lighting wiring issues on this level.': 'Nessun problema nel cablaggio luci su questo livello.', 'Cable continuity': 'Continuità cavo', 'Select a light point to identify every switch with documented cable continuity.': 'Seleziona un punto luce per individuare ogni interruttore con continuità del cablaggio documentata.', 'controlling switch': 'interruttore di comando', 'controlling switches': 'interruttori di comando', 'No controlling switch': 'Nessun interruttore di comando', 'No light points on this level.': 'Nessun punto luce su questo livello.', 'Controlling switches blink red in the 3D view.': 'Gli interruttori di comando lampeggiano in rosso nella vista 3D.', 'No complete switch-to-light cable path is documented.': 'Non è documentato alcun percorso completo dall’interruttore al punto luce.', 'Saved locally': 'Salvato in locale', 'Autosave is not working. Click to retry.': 'Il salvataggio automatico non funziona. Fai clic per riprovare.', 'Unsaved changes are being stored locally.': 'Le modifiche non salvate vengono archiviate in locale.', 'Autosave error': 'Errore salvataggio automatico', 'Saving locally': 'Salvataggio in locale'
  , 'Review physical clearances, coordinated route layouts, cable lengths, continuity, and unconnected devices.': 'Controlla distanze fisiche, layout coordinati dei percorsi, lunghezze, continuità e dispositivi non collegati.'
  , 'Route layout and clearance': 'Layout e distanze dei percorsi', 'No physical conflicts or coordinated layout improvements detected.': 'Nessun conflitto fisico o miglioramento coordinato del layout rilevato.'
  , 'Coordinate': 'Coordina', 'fewer turns': 'curve in meno', 'conflicts removed': 'conflitti rimossi', 'Review model': 'Controlla modello'
  , 'No coordinated route improvements are available.': 'Non sono disponibili miglioramenti coordinati dei percorsi.', 'Coordinated route layout': 'Layout coordinato dei percorsi', 'Coordinated route layout applied.': 'Layout coordinato dei percorsi applicato.'
  , 'Coordinated route layout review': 'Controllo layout coordinato dei percorsi', 'Layout proposal': 'Proposta layout', 'Close route layout review': 'Chiudi controllo layout percorsi'
  , 'Coordinated proposal in model': 'Proposta coordinata nel modello', 'Current route layout in model': 'Layout corrente nel modello', 'The complete affected route set is previewed and applied together.': 'L’intero gruppo di percorsi interessati viene mostrato in anteprima e applicato insieme.'
  , 'Current turns': 'Curve attuali', 'Proposed turns': 'Curve proposte', 'Fewer turns': 'Curve in meno', 'Conflicts removed': 'Conflitti rimossi', 'Length change': 'Variazione lunghezza', 'routes coordinated on this floor': 'percorsi coordinati su questo piano'
  , 'Show original': 'Mostra originale', 'Show coordinated solution': 'Mostra soluzione coordinata', 'Skip / next': 'Salta / successivo', 'Apply all routes': 'Applica tutti i percorsi', 'Route conflict': 'Conflitto percorso'
  , 'Administration': 'Amministrazione', 'Local application branding and privacy': 'Marchio locale e privacy dell’applicazione', 'Application-wide local settings that are never stored in project backups.': 'Impostazioni locali dell’applicazione che non vengono mai salvate nei backup dei progetti.'
  , 'Application icon': 'Icona applicazione', 'The public source and installer always use the neutral icon. A private replacement is stored only in this local browser or desktop profile.': 'Il sorgente pubblico e l’installer usano sempre l’icona neutra. Un’icona privata sostitutiva viene salvata solo in questo profilo locale del browser o dell’app desktop.'
  , 'Choose local icon': 'Scegli icona locale', 'Use neutral icon': 'Usa icona neutra', 'Choose a PNG, JPEG, or WebP image.': 'Scegli un’immagine PNG, JPEG o WebP.', 'The application icon must be smaller than 4 MB.': 'L’icona dell’applicazione deve essere più piccola di 4 MB.', 'The application icon could not be read.': 'Impossibile leggere l’icona dell’applicazione.', 'Unsupported application icon data.': 'Dati dell’icona dell’applicazione non supportati.'
  , 'Project tutorial': 'Tutorial del progetto', 'Step {current} of {total}': 'Passaggio {current} di {total}', 'Skip tutorial': 'Salta tutorial', 'Back': 'Indietro', 'Next': 'Avanti', 'Finish': 'Fine'
  , 'Welcome to the infrastructure editor': 'Benvenuto nell’editor degli impianti', 'This short tour shows the main areas. Everything in the project stays on this computer.': 'Questo breve tour mostra le aree principali. Tutti i dati del progetto restano su questo computer.'
  , 'Levels and blueprints': 'Livelli e planimetrie', 'Switch level here, open the level manager, and calibrate blueprint underlays before drawing.': 'Da qui puoi cambiare livello, aprire la gestione dei piani e calibrare le planimetrie prima di disegnare.'
  , 'Creation tools': 'Strumenti di creazione', 'Create walls, rooms, structures, devices, routes, containers, and measurements from this area.': 'Da quest’area puoi creare pareti, stanze, strutture, dispositivi, percorsi, contenitori e misure.'
  , '3D workspace': 'Area di lavoro 3D', 'Draw and select in the model. Orbit with right drag, pan with middle drag, and zoom with the wheel.': 'Disegna e seleziona nel modello. Ruota con il trascinamento destro, sposta con quello centrale e usa la rotella per lo zoom.'
  , 'Properties and dimensions': 'Proprietà e dimensioni', 'The selected wall, device, route, room, or measurement is edited precisely in this panel.': 'In questo pannello puoi modificare con precisione pareti, dispositivi, percorsi, stanze e misure selezionate.'
  , 'Inspect concealed services': 'Ispeziona gli impianti nascosti', 'X-ray makes structures transparent and enables route selection. Press X to toggle it quickly.': 'I raggi X rendono trasparenti le strutture e permettono di selezionare i percorsi. Premi X per attivarli rapidamente.'
  , 'Project overview': 'Riepilogo progetto', 'Open the complete project report with quantities, route inventory, rooms, assets, and interactive summaries.': 'Apre il rapporto completo del progetto con quantità, inventario dei percorsi, stanze, elementi e riepiloghi interattivi.'
  , 'Lighting view': 'Vista illuminazione', 'Inspect light points, switches, and their documented cable continuity on the active level.': 'Controlla punti luce, interruttori e la continuità documentata dei cavi sul livello attivo.'
  , 'Photo documentation': 'Documentazione fotografica', 'Place categorized photo points in the model and keep local installation pictures with the project.': 'Posiziona punti foto classificati nel modello e conserva nel progetto le immagini locali dell’installazione.'
  , 'Project rules': 'Regole del progetto', 'Settings contains route planning, bend radii, clearances, appearance, device defaults, and project diagnostics.': 'Le impostazioni contengono pianificazione dei percorsi, raggi di curvatura, distanze, aspetto, valori predefiniti dei dispositivi e diagnostica.'
  , 'Standard camera views': 'Viste standard della telecamera', 'Views contains the common camera commands for the model, including the orthographic Top view.': 'Il menu Viste contiene i comandi comuni della telecamera, inclusa la vista ortografica dall’alto.'
  , 'Top view': 'Vista dall’alto', 'Top first switches to orthographic projection and then looks straight down, giving you a precise 2D plan view.': 'Vista dall’alto passa prima alla proiezione ortografica e poi guarda perpendicolarmente verso il basso, offrendo una pianta 2D precisa.'
  , '2D View': 'Vista 2D', 'Enable 2D orthographic plan view': 'Attiva la vista in pianta ortografica 2D', 'Disable 2D view and return to perspective': 'Disattiva la vista 2D e torna alla prospettiva'
  , '2D plan view': 'Vista in pianta 2D', 'Toggle a fixed orthographic top view for precise plan editing, then switch it off to return to 3D perspective.': 'Attiva una vista ortografica fissa dall’alto per modificare con precisione la pianta, poi disattivala per tornare alla prospettiva 3D.'
  , 'Door': 'Porta', 'Window': 'Finestra'
  , 'X and Y move on the plan; Z is vertical. Automatic crossing hills are excluded from this list.': 'X e Y si muovono sulla pianta; Z è verticale. I raccordi automatici degli incroci non compaiono in questo elenco.'
  , 'Calibrate image': 'Calibra immagine', 'Blueprint calibration': 'Calibrazione planimetria', 'Scale line': 'Linea di scala', 'Alignment point': 'Punto di allineamento', 'North arrow': 'Freccia nord', 'Close calibration': 'Chiudi calibrazione'
};
