import { useMemo, useState } from 'react';
import type { AssociationType, DeviceType, MountingFace, ProjectSnapshot } from '../../shared/types';
import { useI18n } from '../lib/i18n';
import { DraftNumberInput } from './DraftNumberInput';
import { ObjectPreview3D } from './ObjectPreview3D';

interface Props { project: ProjectSnapshot; onCreate: (type: DeviceType) => void; onClose: () => void }

export function CustomDeviceTypeDialog({ project, onCreate, onClose }: Props) {
  const { t } = useI18n(); const categories = useMemo(() => project.categories.filter((item) => !['structural', 'transitions', 'storage'].includes(item.serviceCategory)), [project.categories]);
  const [categoryId, setCategoryId] = useState(categories.find((item) => item.id === 'generic')?.id ?? categories[0]?.id ?? 'generic');
  const category = categories.find((item) => item.id === categoryId) ?? categories[0]; const [name, setName] = useState(''); const [shape, setShape] = useState<DeviceType['shape']>('box'); const [dimensions, setDimensions] = useState({ width: 15, height: 10, depth: 8 }); const [color, setColor] = useState(category?.color ?? '#6b747b'); const [backFace, setBackFace] = useState<MountingFace>('back'); const [association, setAssociation] = useState<AssociationType>('wall');
  const previewType: Pick<DeviceType, 'id' | 'name' | 'shape' | 'defaultDimensions'> = { id: 'custom-preview', name: name || 'Custom', shape, defaultDimensions: { width: Math.round(dimensions.width * 10), height: Math.round(dimensions.height * 10), depth: Math.round(dimensions.depth * 10) } };
  const create = () => { if (!name.trim() || !category) return; onCreate({ id: crypto.randomUUID(), categoryId: category.id, name: name.trim(), serviceCategory: category.serviceCategory, shape, defaultDimensions: { width: Math.round(dimensions.width * 10), height: Math.round(dimensions.height * 10), depth: Math.round(dimensions.depth * 10) }, defaultDisplayColor: color, family: 'device', defaultBackFace: backFace, defaultAssociation: association, defaultPorts: [], custom: true }); };
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div className="custom-device-dialog" role="dialog" aria-modal="true" aria-label={t('Create custom device type')}><header><div><strong>{t('Create custom device type')}</strong><span>{t('Preview')}</span></div><button aria-label="Close" onClick={onClose}>×</button></header><div className="custom-device-body"><section>
    <label className="field"><span>{t('Name')}</span><input autoFocus value={name} onChange={(event) => setName(event.target.value)} /></label>
    <label className="field"><span>{t('Category')}</span><select value={categoryId} onChange={(event) => { const next = categories.find((item) => item.id === event.target.value); setCategoryId(event.target.value); if (next) setColor(next.color); }}>{categories.map((item) => <option key={item.id} value={item.id}>{t(item.name)}</option>)}</select></label>
    <label className="field"><span>Default association</span><select value={association} onChange={(event) => setAssociation(event.target.value as AssociationType)}><option value="wall">Wall</option><option value="floor">Floor</option><option value="ceiling">Ceiling</option><option value="free">Free</option></select></label>
    <div className="field"><span>{t('Shape')}</span><div className="shape-choice">{(['box','plate','cylinder','camera'] as const).map((value) => <button key={value} className={shape === value ? 'active' : ''} onClick={() => setShape(value)}>{t(value[0].toUpperCase() + value.slice(1))}</button>)}</div></div>
    <div className="field-grid"><label className="field"><span>{t('Width')}</span><span className="input-with-suffix"><DraftNumberInput min={.1} value={dimensions.width} onCommit={(width) => setDimensions((item) => ({ ...item, width }))} /><em>cm</em></span></label><label className="field"><span>{t('Height')}</span><span className="input-with-suffix"><DraftNumberInput min={.1} value={dimensions.height} onCommit={(height) => setDimensions((item) => ({ ...item, height }))} /><em>cm</em></span></label><label className="field"><span>{t('Depth')}</span><span className="input-with-suffix"><DraftNumberInput min={.1} value={dimensions.depth} onCommit={(depth) => setDimensions((item) => ({ ...item, depth }))} /><em>cm</em></span></label><label className="field"><span>{t('Display color')}</span><input type="color" value={color} onChange={(event) => setColor(event.target.value)} /></label></div>
  </section><section className="device-preview interactive-device-preview"><span>{t('Preview')}</span><ObjectPreview3D type={previewType} color={color} backFace={backFace} onBackFaceChange={setBackFace} /><strong>{name || t('Custom')}</strong><small>{dimensions.width} × {dimensions.height} × {dimensions.depth} cm</small><p>The face marked BACK will touch the selected association surface.</p></section></div><footer><button onClick={onClose}>{t('Cancel')}</button><button className="primary" disabled={!name.trim()} onClick={create}>{t('Create device type')}</button></footer></div></div>;
}
